// src/components/QRScanner.tsx
import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { QrCode, CheckCircle, XCircle, Camera, Loader2, Award, Upload, X, ShieldCheck } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface QRScannerProps {
  isOpen: boolean;
  onClose: () => void;
  onPointsEarned: (points: number) => void;
}

// ── QR Validation ─────────────────────────────────────────────────────────────
// Employee QR format: SWACHH-EMP-{employeeId}-{timestamp}
// Only QR codes matching this format are valid and award points.
const parseEmployeeQR = (data: string): { valid: true; employeeId: string } | { valid: false } => {
  const parts = data.trim().split("-");
  // Must be: SWACHH - EMP - {empId} - {timestamp}  → at least 4 parts
  if (parts.length >= 4 && parts[0] === "SWACHH" && parts[1] === "EMP") {
    const employeeId = parts[2];
    return { valid: true, employeeId };
  }
  return { valid: false };
};

const QRScanner = ({ isOpen, onClose, onPointsEarned }: QRScannerProps) => {
  const [isScanning, setIsScanning]   = useState(false);
  const [scanMode, setScanMode]       = useState<"camera" | "upload" | null>(null);
  const [cameraStream, setCameraStream] = useState<MediaStream | null>(null);
  const [scanResult, setScanResult]   = useState<{
    success: boolean;
    employeeId?: string;
    points: number;
    reason?: string;
  } | null>(null);

  const { toast }    = useToast();
  const videoRef     = useRef<HTMLVideoElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Clean up camera on unmount
  useEffect(() => {
    return () => stopCamera();
  }, []);

  const stopCamera = () => {
    if (cameraStream) {
      cameraStream.getTracks().forEach(t => t.stop());
      setCameraStream(null);
    }
  };

  const startCameraScanning = async () => {
    try {
      setIsScanning(true);
      setScanMode("camera");

      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment" },
      });
      setCameraStream(stream);

      if (videoRef.current) {
        videoRef.current.srcObject = stream;
      }

      // In a production app, use @zxing/browser for real QR decoding.
      // For this demo, we simulate detecting the employee QR after 3 seconds.
      // The simulation uses the correct SWACHH-EMP format so validation passes.
      setTimeout(() => {
        const demoEmployeeId = "EMP" + Math.floor(Math.random() * 900 + 100);
        const simulatedQRData = `SWACHH-EMP-${demoEmployeeId}-${Date.now()}`;
        handleQRCodeDetected(simulatedQRData);
      }, 3000);

    } catch {
      toast({
        title: "Camera Error",
        description: "Unable to access camera. Please check permissions.",
        variant: "destructive",
      });
      setIsScanning(false);
      setScanMode(null);
    }
  };

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setIsScanning(true);
    setScanMode("upload");

    // Simulate reading the QR from the uploaded image.
    // In production, use @zxing/browser BrowserQRCodeReader to decode the actual image.
    setTimeout(() => {
      const demoEmployeeId = "EMP" + Math.floor(Math.random() * 900 + 100);
      const simulatedQRData = `SWACHH-EMP-${demoEmployeeId}-${Date.now()}`;
      handleQRCodeDetected(simulatedQRData);
    }, 2000);
  };

  const handleQRCodeDetected = (qrData: string) => {
    stopCamera();

    const parsed = parseEmployeeQR(qrData);

    if (parsed.valid) {
      const result = { success: true, employeeId: parsed.employeeId, points: 25 };
      setScanResult(result);
      setIsScanning(false);
      onPointsEarned(25);
      toast({
        title: "Verified! Great job! 🎉",
        description: `Employee ${parsed.employeeId} confirmed. +25 points earned!`,
      });
    } else {
      setScanResult({
        success: false,
        points: 0,
        reason: "This QR code was not generated by a Swachh Buddy employee. Only scan the QR shown by your municipal waste collector.",
      });
      setIsScanning(false);
      toast({
        title: "Invalid QR Code",
        description: "This is not a valid Swachh Buddy employee QR code.",
        variant: "destructive",
      });
    }
  };

  const handleClose = () => {
    stopCamera();
    setScanResult(null);
    setIsScanning(false);
    setScanMode(null);
    onClose();
  };

  const resetScanner = () => {
    stopCamera();
    setScanResult(null);
    setIsScanning(false);
    setScanMode(null);
  };

  if (!isOpen) return null;

  return (
    <AlertDialog open={isOpen} onOpenChange={handleClose}>
      <AlertDialogContent className="max-w-md">
        <AlertDialogHeader>
          <AlertDialogTitle className="flex items-center gap-2">
            <QrCode className="h-5 w-5" />
            QR Code Scanner
          </AlertDialogTitle>
          <AlertDialogDescription>
            Scan the QR code shown by your municipal waste collector to verify disposal and earn +25 points.
          </AlertDialogDescription>
        </AlertDialogHeader>

        <div className="py-4">

          {/* Step 1 — Choose scan method */}
          {!scanMode && !scanResult && (
            <div className="text-center space-y-4">
              <div className="mx-auto p-6 bg-primary/10 rounded-full w-24 h-24 flex items-center justify-center">
                <QrCode className="h-12 w-12 text-primary" />
              </div>

              <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-left">
                <p className="text-xs text-amber-700 font-medium mb-1">⚠️ Important</p>
                <p className="text-xs text-amber-600">
                  Only scan QR codes shown by your official municipal waste collector.
                  QR codes from other sources will not be accepted.
                </p>
              </div>

              <div className="space-y-3">
                <Button variant="default" size="lg" onClick={startCameraScanning} className="w-full gap-2">
                  <Camera className="h-4 w-4" /> Use Camera
                </Button>
                <Button variant="outline" size="lg" onClick={() => fileInputRef.current?.click()} className="w-full gap-2">
                  <Upload className="h-4 w-4" /> Upload from Gallery
                </Button>
              </div>

              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleFileUpload}
                className="hidden"
              />
            </div>
          )}

          {/* Step 2a — Camera scanning */}
          {scanMode === "camera" && isScanning && (
            <div className="text-center space-y-4">
              <div className="relative">
                <video
                  ref={videoRef}
                  autoPlay
                  playsInline
                  muted
                  className="w-full max-w-sm mx-auto rounded-lg bg-black"
                  style={{ aspectRatio: "1" }}
                />
                {/* Corner guides */}
                <div className="absolute inset-0 pointer-events-none">
                  <div className="absolute top-4 left-4 w-6 h-6 border-l-2 border-t-2 border-primary" />
                  <div className="absolute top-4 right-4 w-6 h-6 border-r-2 border-t-2 border-primary" />
                  <div className="absolute bottom-4 left-4 w-6 h-6 border-l-2 border-b-2 border-primary" />
                  <div className="absolute bottom-4 right-4 w-6 h-6 border-r-2 border-b-2 border-primary" />
                </div>
              </div>
              <p className="text-sm text-muted-foreground">Position the employee QR code within the frame…</p>
              <Button variant="outline" onClick={resetScanner} className="gap-2">
                <X className="h-4 w-4" /> Cancel
              </Button>
            </div>
          )}

          {/* Step 2b — Upload processing */}
          {scanMode === "upload" && isScanning && (
            <div className="text-center space-y-4">
              <div className="mx-auto p-6 bg-primary/10 rounded-full w-24 h-24 flex items-center justify-center">
                <Loader2 className="h-12 w-12 text-primary animate-spin" />
              </div>
              <p className="text-muted-foreground text-sm">Reading QR code from image…</p>
            </div>
          )}

          {/* Step 3 — Result */}
          {scanResult && (
            <div className="text-center space-y-4">
              <div className={`mx-auto p-6 rounded-full w-24 h-24 flex items-center justify-center ${
                scanResult.success ? "bg-green-50" : "bg-red-50"
              }`}>
                {scanResult.success
                  ? <CheckCircle className="h-12 w-12 text-green-600" />
                  : <XCircle className="h-12 w-12 text-red-500" />
                }
              </div>

              <h3 className={`text-lg font-bold ${scanResult.success ? "text-green-700" : "text-red-600"}`}>
                {scanResult.success ? "Verification Successful!" : "Invalid QR Code"}
              </h3>

              {scanResult.success ? (
                <div className="space-y-2">
                  <div className="flex items-center justify-center gap-2 bg-green-50 border border-green-200 rounded-lg p-3">
                    <ShieldCheck className="h-5 w-5 text-green-600 flex-shrink-0" />
                    <div className="text-left">
                      <p className="text-xs text-green-700 font-medium">Employee Verified</p>
                      <p className="text-xs text-green-600">ID: {scanResult.employeeId}</p>
                    </div>
                  </div>
                  <div className="flex items-center justify-center gap-2">
                    <Award className="h-5 w-5 text-primary" />
                    <span className="font-bold text-primary text-lg">+{scanResult.points} Points Earned!</span>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Disposal verified by official municipal collector.
                  </p>
                </div>
              ) : (
                <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-left">
                  <p className="text-xs text-red-700 font-medium mb-1">Why was this rejected?</p>
                  <p className="text-xs text-red-600">{scanResult.reason}</p>
                </div>
              )}
            </div>
          )}
        </div>

        <AlertDialogFooter>
          {scanResult ? (
            <>
              {!scanResult.success && (
                <Button variant="outline" onClick={resetScanner} className="mr-auto">
                  Try Again
                </Button>
              )}
              <AlertDialogAction onClick={handleClose}>Done</AlertDialogAction>
            </>
          ) : (
            <AlertDialogAction onClick={handleClose}>Cancel</AlertDialogAction>
          )}
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
};

export default QRScanner;